### ISSUE TITLE
Please answer

### ISSUE THREAD

**Issue by dongpu1813** [Original-Tasty/yiimp#2]
![image](https://user-images.githubusercontent.com/42663880/104017709-909c5780-51f3-11eb-9d13-25fd038dd925.png)

help please

**Comment by Original-Tasty** [comment]
> 
> 
> ![image](https://user-images.githubusercontent.com/42663880/104017709-909c5780-51f3-11eb-9d13-25fd038dd925.png)
> 
> help please

Hi, everything seems ok though, what do you need help with exactly?

**Comment by dongpu1813** [comment]
A miner is mining multiple coins

**Comment by Original-Tasty** [comment]
> 
> 
> A miner is mining multiple coins

Are you sure? It seems only to be Galax GTX from screenshot is it?  

Have you set up the dedicated ports for each coins too?

**Comment by dongpu1813** [comment]
There is no dedicated port for each coin
dif123.club   pool

**Comment by Original-Tasty** [comment]
> dif123.club

Oh ok yes the dedicated ports must be set up and mostly the miner must specify at least the coin they're willing to mine.

example in the password field of the miner, it should be  _c=zen_  or _c=bgem_

**Comment by Original-Tasty** [comment]
IS it ok?

**Comment by Original-Tasty** [comment]
> 
> 
> There is no dedicated port for each coin
> dif123.club pool
> https://discord.com/

Is it ok?
